import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-green-800 text-white px-3 py-5 flex justify-between items-center">
          <h1 className="text-xl cursor-pointer hover:underline">
            <Link href="/">SSCGI LMS</Link>
          </h1>
          <div className="text-right">
            <p className="cursor-pointer hover:underline">
              <Link href="/profile">Reyes, Christian</Link>
            </p>
            <p className="text-sm">Student</p>
          </div>
        </header>
        <main className="py-5 px-3">{children}</main>
        <footer className="bg-gray-700 text-white px-3 py-5">
          All Rights Reserved
        </footer>
      </body>
    </html>
  );
}
